sudo: false
addons:
  apt:
    packages:
      - rake
      - bison
      - git
      - gperf
language: c
compiler:
  - gcc
  - clang
before_script:
  - redis-server --port 6379 &
  - redis-server --port 6380 --requirepass 'secret' &
script:
  - rake test
notifications:
  irc:
    channels:
      - "irc.freenode.org#backdoor-log"
    on_success: always
    on_failure: always
    use_notice: true
    skip_join: true
    template:
        - "[%{message}] %{repository} (%{commit}) by %{author}: See %{build_url}"
  webhooks:
    - secure: "B40Dmvt0JkAQA/dfhUP+NYFI37pBkxRBrc+XudT2bCilj3Z99B1l36oHxfy9Ate01yDPNrq7pCT2WGmLhfumXwwiucxcSpCg06D563IPZsrc4fnhqwTyWzTu8YUvEYgUONG5gokPOAIP9yGXNbyel9+wPVZitOkVTPRrm3PNbiE="

